site_name: LM35 Arduino library
site_url: https://miguelloureiro98.github.io/LM35IC/
repo_url: https://github.com/MiguelLoureiro98/LM35IC

theme:
  #logo: logos/logo.jpg
  #favicon: logos/favicon.jpg
  icon:
    repo: fontawesome/brands/github
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
      primary: teal
      accent: green
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
      primary: teal
      accent: green

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/miguel-santos-loureiro/
      name: Miguel Loureiro's LinkedIn page
    - icon: fontawesome/brands/github
      link: https://github.com/MiguelLoureiro98
      name: Miguel Loureiro's GitHub page

copyright: Copyright &copy; 2024 Miguel Loureiro

plugins:
  - search
#  - mkdoxy:
#      doxygen-bin-path: C:/Program Files/doxygen/bin
#      projects:
#        LM35IC: # name of project must be alphanumeric + numbers (without spaces)
#          src-dirs: src/ # path to source code (support multiple paths separated by space) => INPUT
#          full-doc: True # if you want to generate full documentation
#          doxy-cfg: # standard doxygen configuration (key: value)
#            FILE_PATTERNS: "*.cpp *.h*" # specify file patterns to filter out
#            RECURSIVE: True # recursive search in source directories

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Installation: installation.md
  - Basic usage: basics.md
  - LM35 namespace API: class_API.md
  - About: about.md