site_name: LM35 Arduino library
site_url: https://miguelloureiro98.github.io/LM35IC/
repo_url: https://github.com/MiguelLoureiro98/LM35IC

theme:
  #logo: logos/logo.jpg
  #favicon: logos/favicon.jpg
  icon:
    repo: fontawesome/brands/github
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
      primary: teal
      accent: green
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
      primary: teal
      accent: green

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/miguel-santos-loureiro/
      name: Miguel Loureiro's LinkedIn page
    - icon: fontawesome/brands/github
      link: https://github.com/MiguelLoureiro98
      name: Miguel Loureiro's GitHub page

copyright: Copyright &copy; 2024 Miguel Loureiro

plugins:
  - search
  - mkdoxy:
      projects:
        LM35IC: # name of project must be alphanumeric + numbers (without spaces)
          src-dirs: src/ # path to source code (support multiple paths separated by space) => INPUT
          full-doc: True # if you want to generate full documentation
          doxy-cfg: # standard doxygen configuration (key: value)
            FILE_PATTERNS: "*.cpp *.h*" # specify file patterns to filter out
            RECURSIVE: True # recursive search in source directories
            JAVADOC_AUTOBRIEF: True
            JAVADOC_BANNER: True
            JAVADOC_BLOCK: True

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Installation: installation.md
  - Basic usage: basics.md
  - API reference: 
    - Main page: API_reference.md
    - API index: LM35IC/annotated.md
    - Namespace list: LM35IC/namespaces.md
    - LM35 namespace: LM35IC/namespaceLM35.md
    - LM35IC class: LM35IC/classLM35_1_1LM35IC.md
  - About: about.md

not_in_nav: |
  /LM35IC/links.md
  /LM35IC/variables.md
  /LM35IC/macros.md
  /LM35IC/functions.md
  /LM35IC/pages.md
  /LM35IC/modules.md
  /LM35IC/namespace_member_enums.md
  /LM35IC/namespace_member_typedefs.md
  /LM35IC/namespace_member_variables.md
  /LM35IC/namespace_member_functions.md
  /LM35IC/namespace_members.md
  /LM35IC/class_members.md
  /LM35IC/class_member_functions.md
  /LM35IC/class_member_variables.md
  /LM35IC/class_member_typedefs.md
  /LM35IC/class_member_enums.md
  /LM35IC/hierarchy.md
  /LM35IC/LM35IC_8h.md
  /LM35IC/LM35IC_8h_source.md
  /LM35IC/LM35IC_8cpp.md
  /LM35IC/LM35IC_8cpp_source.md
  /LM35IC/classes.md
  /LM35IC/files.md
  /LM35IC/dir_68267d1309a1af8e8297ef4c3efbcdba.md