name: Arduino Library specifications

on:
  workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run linter
        uses: arduino/arduino-lint-action@v2
        with:
          library-manager: submit
          compliance: strict
          project-type: library
          recursive: false